// Generate random number Store it in variable -- Guessing Game
// let number = 0
// let chances = 0
// keep asking for the number until correct guess
// Increment the chances variables

// Eventually after the game is over, display the ( 100 - Number of chances) and the actual number

let number1 = Math.floor((Math.random() * 100)+ 1) // Generate random numbers between 1 and 100
let chances = 0 // Initial value of chances taken to guess a number
let guess // Variable to store the number to be input form user to be guessed
console.log("This is a guessing game and you have to enter a number and if it matches with the number generated by the computer, then you win...")
guess = prompt("Enter a number between 1 and 100")
++chances // To increment the number of chances taken

do{
    guess = Number.parseInt(guess)
    if( guess > number1){
        console.log("Number entered is greater")
        guess = prompt("Enter again!!")
        guess = Number.parseInt(guess) 
        ++chances
        continue
    }

    else if ( guess < number1){
        console.log("Number entered is smaller")
        guess = prompt("Enter again!!")
        guess = Number.parseInt(guess) 
        ++chances
        continue
    }
}while(guess != number1)

let score = 100 - chances
console.log("COngratulations... The number generated was", number1 + " and you guessed it right\n Your final score is", score)